[package]
name = "swarm-head"
version = "0.1.0"
edition = "2024"
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
mainline.workspace = true
swarm-protocol = { path = "../swarm-protocol" }
thiserror.workspace = true

[dev-dependencies]
hex.workspace = true
pubky.workspace = true
tokio.workspace = true

[lints]
workspace = true
