[package]
name = "libtorrent-engine"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false
build = false

[dependencies]
cxx = "=1.0.199"
libtorrent-engine-sys = { path = "sys" }
thiserror.workspace = true

[lints]
workspace = true
